@c -*-texinfo-*-
@c This is part of the GNU Guile Reference Manual.
@c Copyright (C)  1996, 1997, 2000, 2001, 2002, 2003, 2004, 2010
@c   Free Software Foundation, Inc.
@c See the file guile.texi for copying conditions.

@node Неодобряемое использование(Deprecation)
@section Deprecation

Время от времени функции и другие элементы Guile устаревают.
Мехнизм Неодобрения(@dfn{deprecation}) Guile может вам помочь справиться
с этим.

Когда вы используете функцию, которая устарела вы скорее всего, получите
предупреждение во время выполнения. Кроме того, если у вас достаточно новый
набор инструментов, использование устаревшей функции из @code{libguile}
вызовет предупрежение во время ликовки(link-time).

Основной источник информации о том, какие интерфейсы устарели в данном релизе
это файл @file{NEWS}.  Этот файл также документирует, что вы должны использовать
вместо устаревшей вещи.

Файл @file{README} содержит инструкуии о том, как контролировать включение или
удаление устаревшей функции из публичного API Guile, и способы управления
устаревшими функциями с помощью предупреждающих сообщений.

Идея этого механизма заключается в том, что обычно все устаревшие интерфейсы
доступны, но вы получаете обратную связь при компиляции и запуске кода, который
их использует. так что вы можете перейти на новый APIs когда появиться свободное
время переписать старые вызовы.